<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OsuGammaChanger.Core\OsuGammaChanger.Core.csproj" />
    <PackageReference Include="OsuMemoryDataProvider" Version="0.12.1" />
  </ItemGroup>

</Project>
